# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: pandp_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./initdb/init-dev-db.sh:/docker-entrypoint-initdb.d/init-dev-db.sh
      - ./initdb/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080